### ISSUE TITLE
You definitely move forward, but i still have issues with entities functions

### ISSUE THREAD

**Issue by OwlBawl** [Rihan9/LD2412#4]
My test ld2412 is firmware 1.24
compiled your updated config

Bluetoth switch doesnt work... and don't show correct state

Mode select only shows state, not change

Presense holding number also don't function..

**Comment by Rihan9** [comment]
Hi Owl,
thanks for your report. Your description is a bit too vague to identify the problem, considering also that I don't reproduce these issues.
So, first of all: after you change one of these configurations do you wait a couple of seconds before change another one? Each change (excluding the mode select) cause the sensor to reboot, so you need to wait for the connecton to be estabilished again, otherwise the command got ignored and the esp got out of sync (You can use the button query parameters to resync it).
If you have waited, can you please set your debug level to very_verbose and post here your log related to the bluetooth switch state change? I need to see if the command is succesfully send and the ack is received

**Comment by OwlBawl** [comment]
Would try later, but anyway sensor like "Bluetooth" don't report their current state even after load/poll/engenering mode

**Comment by Rihan9** [comment]
Ok, so the switch may work, but the status is not correctly reported to HA.
I checked it and the call to get the bluetooth status is missing, but there is a problem: the LD2412 doesn't expose an endpoint in the communication protocol to ask him if his bluetooth is turned on or off. 
So this will be a pain.

**Comment by Rihan9** [comment]
Hi @OwlBawl,
I made some tests. All 3 configuration work as expected (more or less for the latest, see below). 
When the bluetooth is turned off, the mac address is unavailable and the state of the switch is correctly reported, event after a reboot. --> please provide a way to reproduce the issue
The mode selector is responsive, correcty inizialized and the change made on it is reflected on the sensor. --> please provide a way to reproduce the issue
Presense holding number suffer greatly from the reboot after the change as been made. If you edit the value 1 point at time, it can be very unstable. From the app, the reboot doesn't seem required when changing the basic configs, so I'm removing it. Please check the dev branch to see if it's better

**Comment by Rihan9** [comment]
Optimization merged to main. The first two point are still not reporduced so I'm closing this issue.
